[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/hbstack/hb"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params.hb.header]
sticky = true
full_width = true
brand = ""
theme = ""
